const names = require('./4-name')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavor')
require('./7-mind-grenade')
console.log(data)
console.log(names)
sayHi('susan')
sayHi('john')
sayHi('peter')
sayHi(names.john)